[tool.poetry]
name = "noa_tools"
version = "0.1.0-1"
description = ""
authors = ["Noa Nabeshima <noanabeshima@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
tsp-solver = "^0.1"
boto3 = "^1.34.138"
pillow = "^10.4.0"
scipy = "^1.14.0"
einops = "^0.8.0"
matplotlib = "^3.9.0"
openai = "^1.35.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
