[tool.poetry]
name = "ligo.rrt-chat"
version = "0.1.4"
description = ""
authors = ["Sushant Sharma-Chaudhary <sushant.sharma-chaudhary@git.ligo.org>"]
readme = "README.md"
packages = [{include = "ligo"}]

[tool.poetry.dependencies]
python = "^3.9"
safe-netrc = "^1.0.1"
requests = "^2.28.2"

[tool.poetry.dev-dependencies]
pytest = "*"


[build-system]
requires = ["poetry-core>1.0.0"]
build-backend = "poetry.core.masonry.api"
