[tool.poetry]
name = "codefly-cli"
version = "0.0.19"
description = ""
authors = ["Antoine Toussaint <antoine.toussaint@codefly.ai>"]
packages = [{include = "codefly_cli"}]

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^2.7.1"
PyYAML = "^6.0.1"
grpcio = "^1.63.0"
protobuf = "^5.26.1"
grpclib = "^0.4.7"
codefly-sdk = "^0.0.14"
pytest = "^8.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
