[tool.poetry]
name = "spy-spider"
version = "0.1.4"
description = ""
authors = ["mathewgeola <mathewgeola@163.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
httpx = "^0.27.0"
colorlog = "^6.8.2"
ujson = "^5.10.0"
drissionpage = "^4.0.5.4"
typing-extensions = "^4.12.2"
pandas = "^2.2.2"
pyexecjs = "^1.5.1"
py-mini-racer = "^0.6.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
