[package]
name = "passacre"
version = "1.0.1-rc1"
edition = "2021"

[lib]
name = "_passacre_backend"
crate-type = ["cdylib"]

[features]
default = ["python"]
python = ["pyo3"]

[dependencies]
pyo3 = { version = "0.21.1", optional = true }
libc = "0.2.18"
rand = "0.8"
num-bigint = { version = "0.4", features = ["rand"] }
thiserror = "1.0.61"
num-traits = "0.2.19"

[build-dependencies]
cc = "1.0.104"

[dev-dependencies]
parameterized = "2.0.0"
