[tool.poetry]
name = "download_pbi_xmla"
version = "0.2.8.0" # Update this version number for each new release
description = "A package to fetch and save Power BI tables via XMLA endpoint"
authors = ["Danny Bharat <dannybharat@arkimetrix.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
polars = "^0.20.31"
pyodbc = "^5.1.0"
pandas = "^2.2.2"
pythonnet = "^3.0.3"
pyarrow = "^16.1.0"
msal = "^1.29.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"