[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "astmain"
version = "0.0.150"
description = "æè¿°:æˆ‘çš„å·¥å…·åŒ…ðŸ’—2024/07/01ðŸ’—09_31_21#ðŸ’— pip install  astmain==0.0.150  "
dependencies = ["tornado", "pywin32", "requests", "pyppeteer", "pyppeteer_stealth", "arrow"]
readme = "README.md"

[[project.authors]]
name = "xupeng"
email = "1311192345@qq.com"
