[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ppf_approx"
description = "Implementation of the Pade-partial fraction approximation for inverting the Laplace transform of the first passage time distribution."
version = "0.1.1"
readme = "README.md"
authors = [
    { name = "Juan Magalang", email = "jarmsmagalang@gmail.com" }
]
dependencies = [
    "numpy",
    "mpmath",
    "scipy"
]
