[project]
name = "nonebot_plugin_ntqq_restart"
version = "0.2.0"
description = "A plugin for restarting NTQQ when bot disconnection"
authors = [
    { name = "KanbeReina", email = "kano.2525@qq.com" },
]
dependencies = [
    "psutil>=6.0.0",
    "pywin32>=306",
    "pyautoit>=0.6.5",
    "nonebot-plugin-apscheduler>=0.5.0",
    "nonebot2>=2.3.1",
]
requires-python = ">=3.10"
readme = "README.md"

[project.license]
text = "MIT"

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true
