[build-system]
requires = [
    "hatchling>=1.22.2"
]
build-backend = "hatchling.build"

[project]
name = "pypomes_security"
version = "0.2.2"
authors = [
  { name="GT Nunes", email="wisecoder01@gmail.com" }
]
description = "A collection of Python pomes, penyeach (security modules)"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
dependencies = [
    "pip>=24.0",
    "pypomes_core>=1.3.3",
    "setuptools>=69.0.0",
    "wheel>=0.41.0"
]

[project.urls]
"Homepage" = "https://github.com/TheWiseCoder/PyPomes-Security"
"Bug Tracker" = "https://github.com/TheWiseCoder/PyPomes-Security/issues"
