[project]
name = "bfiola-operator-core"
version = "0.2.4-rc.1"
dependencies = [ "fastapi", "kopf", "kubernetes", "pydantic", "uvicorn",]

[project.optional-dependencies]
dev = [ "build", "python-semantic-release", "toml", "twine",]

[tool.semantic_release.branches.dev]
match = "dev"
prerelease = true
prerelease_token = "rc"

[tool.semantic_release.branches.main]
match = "main"
prerelease = false

[tool.setuptools.packages.find]
include = [ "operator_core",]
