[build-system]
requires = ['setuptools',"cython"]
build-backend = 'setuptools.build_meta'


[project]
name='Cheb3D'
version="0.2.2"
description="fitting function with Chebichev polynomial on spectral grid"
readme="README.md"
requires-python = ">=3.8"
authors = [
	{name = "Marco Mancini", email = "marco.mancini@obspm.fr" },
	{name = "Jerome Novak", email = "jerome.novak@astro.unistra.fr" },
	{name = "Eric Gourgoulhon", email = "eric.gourgoulhon@obspm.fr" }
]
maintainers = [
	    {name = "Marco Mancini", email = "marco.mancini@obspm.fr"}
	    ]


classifiers=[
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.12",
	"License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
        "Operating System :: OS Independent",
    ]
