[tool.poetry]
name = "morphdb-utils"
version = "0.2.34"
description = ""
authors = ["shibatanaoto <naoto.shibata510@gmail.com>"]
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.9"
pandas = "^2.1.3"
requests = "2.31.0"
xlrd = "2.0.1"
matplotlib = "3.5.2"
plotly = "5.21.0"
kaleido = "0.2.1"
openpyxl = "^3.1.2"
sqlalchemy = {extras = ["asyncio"], version = "1.4.52"}
pyyaml = "^6.0.1"


[tool.poetry.group.dev.dependencies]
python-dotenv = "^1.0.0"
types-requests = "^2.28.11.13"
pytest = "^7.4.4"
black = "^24.1.0"
flake8 = "^5.0.4"
mypy = "^1.8.0"
pre-commit = "^3.6.0"
types-pytz = "^2023.3.1.1"
pytest-asyncio = "^0.23.3"
wheel = "^0.43.0"
twine = "^5.0.0"
poethepoet = "^0.25.0"
plotly = "^5.21.0"
openai = "^1.34.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poe.tasks]
pub-test = "poetry publish -r testpypi --build"
pub = "poetry publish --build"
