[tool.poetry]
name = "rov-db-access"
version = "1.2.1"
description = ""
authors = ["Pablo Cano <pablo.cano@rovisen.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
geoalchemy2 = "^0.14.2"
sqlalchemy = "^2.0.23"
psycopg2-binary = "^2.9.9"
boto3 = "^1.34.99"
pydantic-settings = "^2.2.1"
shapely = "^2.0.4"
pyproj = "^3.6.1"
rasterio = {version="^1.3.10", extras=["s3"]}
pillow = "^10.3.0"
rov-sent-api = "^0.1.23"
alembic = "^1.13.1"
geojson = "^3.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
