[tool.poetry]
name = "t-fujita"
version = "1.0.0"
description = "pipx run t-fujita"
authors = ["t-fujita <t-fujita@creationline.com>"]
readme = "README.md"
include = ["t_fujita/**/*"]
exclude = ["tests", "*.tests", "*.tests.*", "tests.*", ".venv/**/*"]


[tool.poetry.dependencies]
python = "^3.10"
rich = "^13.7.1"
typer = "^0.12.3"


pipx = "^1.6.0"
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.scripts]
t-fujita = "t_fujita.card:app"
