[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "esp-helper"
authors = [
    {name = "Jake Barbieur", email = "barbieur@gmail.com"}
]
description = "An application for streamlining development with ESP chips."
version = "0.0.6"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "click==8.1.7",
    "requests==2.32.3",
    "beautifulsoup4==4.12.3",
    "pathlib==1.0.1",
    "urllib3==2.2.2"
]
dynamic = ["scripts"]

[tool.setuptools.packages.find]
include = ["*"]
exclude = ["docs*", "tests*", "scripts*"]

[scripts]
esp-helper = "esp_helper.main:main"
