[build-system]
requires = ["hatchling", "cocotb"]
build-backend = "hatchling.build"
[project]
name = "gg_ppv"
version = "0.0.3"
authors = [
  { name="gg", email="grace.moertz1233@gmail.com" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]