[project]
name = "bfiola-devtools"
version = "0.0.2-rc.1"
dependencies = [ "black", "build", "click", "isort", "packaging", "pydantic", "python-semantic-release", "toml", "twine",]

[project.optional-dependencies]
dev = []

[project.scripts]
devtools = "devtools:main"

[tool.setuptools.packages.find]
include = [ "devtools",]
