[project]
name = "dekcli"
version = "0.1.26"
description = ""
authors = [
    { name = "sanzenwin", email = "sanzenwin@gmail.com" },
]
dependencies = [
    "GitPython<=3.1.41",
    "kubernetes<=29.0.0",
    "smbprotocol<=1.10.1",
    "pyinstaller<=6.8.0",
    "pywin32<=306",
    "tqdm<=4.66.4",
    "deksecrets<1.0.0",
    "dekgen<1.0.0",
    "dekvenv<1.0.0",
]
requires-python = ">=3.10,<3.13"
readme = "README.md"

[project.license]
text = "MIT"

[project.scripts]
dekcli = "dekcli.click.__entry__:main"

[tool.pdm.build]
includes = [
    "dekcli",
]

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"
